In [23]:
import pandas as pd

# set display options for better viewing
pd.set_option("display.max_columns", None)
pd.set_option("display.width", 1000)

In [24]:
file_path = "../data/raw/day_ahead_prices_germany_2023_2026.csv"

df = pd.read_csv(file_path, sep=";")
df.head()

             Start date             End date  Germany/Luxembourg [€/MWh] Calculated resolutions  ∅ DE/LU neighbours [€/MWh] Calculated resolutions  Belgium [€/MWh] Calculated resolutions  Denmark 1 [€/MWh] Calculated resolutions  Denmark 2 [€/MWh] Calculated resolutions  France [€/MWh] Calculated resolutions  Netherlands [€/MWh] Calculated resolutions  Norway 2 [€/MWh] Calculated resolutions  Austria [€/MWh] Calculated resolutions  Poland [€/MWh] Calculated resolutions  Sweden 4 [€/MWh] Calculated resolutions  Switzerland [€/MWh] Calculated resolutions  Czech Republic [€/MWh] Calculated resolutions DE/AT/LU [€/MWh] Calculated resolutions  Northern Italy [€/MWh] Calculated resolutions Slovenia [€/MWh] Calculated resolutions  Hungary [€/MWh] Calculated resolutions
0  Jan 1, 2023 12:00 AM  Jan 1, 2023 1:00 AM                                              -5.17                                              13.85                                   -4.39                                      2.01                                      2.01                                   0.00                                       -3.61                                   119.32                                   12.06                                  18.09                                     2.01                                        0.03                                           4.84                                       -                                         195.90                                   13.31                                   19.76
1   Jan 1, 2023 1:00 AM  Jan 1, 2023 2:00 AM                                              -1.07                                               9.79                                   -1.75                                      1.38                                      1.38                                  -0.10                                       -1.46                                   108.83                                   -0.10                                   5.75                                     1.38                                       -7.25                                          -0.35                                       -                                         191.09                                   -0.07                                    0.19
2   Jan 1, 2023 2:00 AM  Jan 1, 2023 3:00 AM                                              -1.47                                               8.91                                   -1.46                                      0.09                                      0.09                                  -1.33                                       -1.52                                   102.39                                   -0.66                                   5.27                                     0.09                                       -3.99                                          -0.97                                       -                                         187.95                                   -0.47                                    0.07
3   Jan 1, 2023 3:00 AM  Jan 1, 2023 4:00 AM                                              -5.08                                               6.58                                   -5.27                                      0.08                                      0.08                                  -4.08                                       -5.00                                    92.36                                   -1.99                                   5.74                                     0.08                                       -7.71                                          -1.93                                       -                                         187.82                                   -1.56                                    0.01
4   Jan 1, 2023 4:00 AM  Jan 1, 2023 5:00 AM                                              -4.49                                               5.42                                   -4.41                                      0.05                                      0.05                                  -4.16                                       -4.60                                    82.66                                   -2.42                                   5.22                                     0.05                                       -9.71                                          -3.07                                       -                                         187.74                                   -1.94                                   -0.77

In [25]:
df = df[[
    "Start date",
    "Germany/Luxembourg [€/MWh] Calculated resolutions"
]]

df.head()

             Start date  Germany/Luxembourg [€/MWh] Calculated resolutions
0  Jan 1, 2023 12:00 AM                                              -5.17
1   Jan 1, 2023 1:00 AM                                              -1.07
2   Jan 1, 2023 2:00 AM                                              -1.47
3   Jan 1, 2023 3:00 AM                                              -5.08
4   Jan 1, 2023 4:00 AM                                              -4.49

In [26]:
df.columns = ["timestamp", "price"]

df.head()

              timestamp  price
0  Jan 1, 2023 12:00 AM  -5.17
1   Jan 1, 2023 1:00 AM  -1.07
2   Jan 1, 2023 2:00 AM  -1.47
3   Jan 1, 2023 3:00 AM  -5.08
4   Jan 1, 2023 4:00 AM  -4.49

In [27]:
df["timestamp"] = pd.to_datetime(df["timestamp"])

df.info()
df.head()

C:\Users\ankit\AppData\Local\Temp\ipykernel_19076\3085886818.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["timestamp"] = pd.to_datetime(df["timestamp"])

<class 'pandas.DataFrame'>
RangeIndex: 27264 entries, 0 to 27263
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   timestamp  27264 non-null  datetime64[us]
 1   price      27264 non-null  float64
dtypes: datetime64[us](1), float64(1)
memory usage: 426.1 KB

            timestamp  price
0 2023-01-01 00:00:00  -5.17
1 2023-01-01 01:00:00  -1.07
2 2023-01-01 02:00:00  -1.47
3 2023-01-01 03:00:00  -5.08
4 2023-01-01 04:00:00  -4.49

In [28]:
df = df.sort_values(by="timestamp").reset_index(drop=True)

In [29]:
df.isnull().sum()

timestamp    0
price        0
dtype: int64

In [30]:
df.head()

            timestamp  price
0 2023-01-01 00:00:00  -5.17
1 2023-01-01 01:00:00  -1.07
2 2023-01-01 02:00:00  -1.47
3 2023-01-01 03:00:00  -5.08
4 2023-01-01 04:00:00  -4.49

In [31]:
df.tail()

                timestamp   price
27259 2026-02-09 19:00:00  165.81
27260 2026-02-09 20:00:00  144.13
27261 2026-02-09 21:00:00  134.60
27262 2026-02-09 22:00:00  122.90
27263 2026-02-09 23:00:00  108.92

In [32]:
full_range = pd.date_range(
    start=df["timestamp"].min(),
    end=df["timestamp"].max(),
    freq="h"
)

len(full_range)

27264

In [33]:
len(df)

27264

In [34]:
missing_timestamps = full_range.difference(df["timestamp"])

len(missing_timestamps)

3

In [35]:
missing_timestamps[:10]

DatetimeIndex(['2023-03-26 02:00:00', '2024-03-31 02:00:00', '2025-03-30 02:00:00'], dtype='datetime64[us]', freq=None)

In [36]:
df["timestamp"].duplicated().sum()

np.int64(3)

In [37]:
df[df["timestamp"].duplicated(keep=False)]

                timestamp  price
7225  2023-10-29 02:00:00   0.01
7226  2023-10-29 02:00:00   0.02
15961 2024-10-27 02:00:00  82.23
15962 2024-10-27 02:00:00  80.43
24697 2025-10-26 02:00:00   3.19
24698 2025-10-26 02:00:00   2.02

In [38]:
df = df.groupby("timestamp", as_index=False).mean()

In [39]:
df["timestamp"].duplicated().sum()

np.int64(0)

In [40]:
len(df)
df = df.set_index("timestamp")
df = df.sort_index()

print(df.head())
print(df.columns)
print(df.shape)

                     price
timestamp
2023-01-01 00:00:00  -5.17
2023-01-01 01:00:00  -1.07
2023-01-01 02:00:00  -1.47
2023-01-01 03:00:00  -5.08
2023-01-01 04:00:00  -4.49
Index(['price'], dtype='str')
(27261, 1)

In [41]:
df.to_csv("../data/processed/clean_price_data.csv")